name: Project-1

services:
    web:
        build: .
        container_name: apache_php
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db

    db:
        image: mariadb:11.8
        container_name: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root123
            MARIADB_DATABASE: database1
            MARIADB_USER: user
            MARIADB_PASSWORD: user123
        ports:
            - 3306:3306
        volumes:
            - ./db_data:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin:5.2
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 8081:80
